# Commenter les ports une fois en production pour reduire les risques d'attaques
# et faire le nginx.conf pour faire le reverse proxy

services:
  frontend:
    build: front
    networks:
      - gamerev

  backend:
    build: backend
    networks:
      - gamerev
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18.4-alpine
    volumes:
      - postgre-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - gamerev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"   # HTTP → redirect vers HTTPS
      - "8443:443"  # HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs # copier les certificats dans le container
    depends_on:
      - frontend
      - backend
    networks:
      - gamerev

  prometheus:
    image: prom/prometheus:v3.12.0
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - gamerev


  grafana:
    container_name: grafana
    image: grafana/grafana:12.4
    env_file:
      - .env
    networks:
      - gamerev
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro

    depends_on:
      - prometheus

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.16.0
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_URI: "postgres:5432/${DB_NAME}?sslmode=disable"
      DATA_SOURCE_USER: ${DB_USER}
      DATA_SOURCE_PASS: ${DB_PASS}
    networks:
      - gamerev
    depends_on:
      postgres:
        condition: service_healthy

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    container_name: nginx-exporter
    command:
      - "--nginx.scrape-uri=http://nginx:8080/stub_status"
    networks:
      - gamerev
    depends_on:
      - nginx

networks:
  gamerev:
    driver: bridge

volumes:
  postgre-data:
    driver: local
  grafana-data:
    driver: local
