services:
  frontend:
    build: front
    ports:
      - "8080:80"
    networks:
      - gamerev
  backend:
    build: backend
    ports:
      - "4000:4000"
    networks:
      - gamerev
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgre-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}


networks:
  gamerev:
    driver: bridge

volumes:
  postgre-data:
    driver: local
