services:
  frontend:
    ports:
      - "8080:80"

  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"

  postgres:
    ports:
      - "5433:5432"

  grafana:
    ports:
      = "3000:3000"
