server {
	listen 8080;

	server_name localhost;

	return 301 https://$host:8443$request_uri;
	# on redirigie toutes les reuquets en https sur le port 8443
	# host permet de garder lip ou le domaine de la requete initiale
	# reques_uri permet de garder le chemin de la reuquet initale
}
