# comment configurer la redirection de nginx pour le front et le back

server {
    listen 80;
    server_name localhost www.gamerev.local;
    return 301 https://$host$request_uri;   # http vers https
}

server {
	listen 8080;

	location /stub_status {
		stub_status;
	}
}

server {
    listen 443 ssl;
    server_name localhost www.gamerev.local;

    ssl_certificate /etc/nginx/certs/cert.crt;
    ssl_certificate_key /etc/nginx/certs/key.key;

    location /api/ {
        proxy_pass http://backend:4000; # Redirige vers le backend
    }

    location / {
        proxy_pass http://frontend:80; # Redirige vers le frontend
    }

}

