# Stage 1 : Build
FROM docker.io/library/node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN ["npm", "run", "build"]

# Stage 2 : servir

FROM docker.io/library/nginx:alpine

EXPOSE 80

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

