services:

  vault-init:
    image: alpine:3.19
    volumes:
      - vault_data:/vault/data
      - vault_logs:/vault/logs
      - vault_file:/vault/file
    command: chown -R 100:100 /vault/data /vault/logs /vault/file

  vault:
    image: hashicorp/vault:1.17
    restart: unless-stopped
    container_name: vault
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_SKIP_VERIFY=true
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - vault_data:/vault/data
      - vault_logs:/vault/logs
      - vault_file:/vault/file
      - ./vault/config:/vault/config:ro
      # - ./vault/certs:/certs:ro
    command: vault server -config=/vault/config/vault.hcl -log-level="info"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8200/v1/sys/health?standbyok=true&sealedcode=200&uninitcode=200"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      vault-init:
        condition: service_completed_successfully

  vault-unsealer:
    image: alpine:3.19
    container_name: vault-unsealer
    depends_on:
      - vault
    volumes:
      - ./unsealer/unseal.sh:/unseal.sh:ro
      - ./vault_keys:/vault_keys
    command: sh -c "apk add --no-cache curl jq && sh /unseal.sh"
    restart: on-failure

  vault-bootstrap:
    container_name: vault-bootstrap
    image: alpine:3.19
    environment:
      - CYBER_PASSWORD=${CYBER_PASSWORD}
    volumes:
      - ./vault/bootstrap.sh:/bootstrap.sh:ro
      - ./vault/policies:/vault/policies:ro
      - ./vault_keys/root_keys.json:/vault_keys/root_keys.json:ro
      - ./approle_id:/approle_id
    command: sh -c "apk add --no-cache curl jq && sh /bootstrap.sh"
    depends_on:
      vault-unsealer:
        condition: service_completed_successfully

  vault-healthcheck:
    image: alpine:3.19
    container_name: vault-healthcheck
    depends_on:
      - vault
    volumes:
      - ./healthcheck/check.sh:/check.sh:ro
    command: sh -c "apk add --no-cache curl jq && sh /check.sh"
    restart: unless-stopped

volumes:
  vault_data:
  vault_logs:
  vault_file:
